STORE_DIR = (
    "bids",
    "brainager",
    "cat12",
    "eddyqc",
    "fcn",
    "fmriprep-anat",
    "fmriprep-cuff",
    "fmriprep-rest",
    "freesurfer",
    "fslanat",
    "gift_rest",
    "mriqc",
    "qsiprep-V1",
    "signatures",
)
